
linters:
  enable:
    - goconst
    - goimports
    - gocritic
    - revive
    - misspell
    - stylecheck
    - unconvert
    - unparam
    - gocheckcompilerdirectives
    - gofmt

linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  goheader:
    values:
      const:
        # Define here const type values in format k:v.
        # For example:
        COMPANY: KKRT Labs
        YEAR: "2024"
        PROJECT: Kakarot Controller
        SPDX: Unlicense
    template: |-
      SPDX-License-Identifier: {{ SPDX }}
      (c) Copyright {{ YEAR }} {{ COMPANY }} all rights reserved.
      This file is part of the project {{ PROJECT }}.

issues:
  max-same-issues: 10
  exclude-dirs:
    - .gocache
    - build
    - mock
    - deps
    - vendor
  exclude-files:
    # skip files copied from geth
    - pkg/ethereum/trie/encoding_test.go
    - pkg/ethereum/trie/encoding.go
    - pkg/ethereum/trie/hasher.go
    - pkg/ethereum/trie/node_enc.go
    - pkg/ethereum/trie/node.go
run:
  timeout: 20m
  
  
